CSC BDSE: Task 1
Charmed-BDSE-fans/csc-bdse pull request #3
Opened 2018-03-01 18:50 UTC by LDVSOFT

2018-03-05 18:17 UTC, semkagtn approved these changes

2018-03-05 18:17 UTC, semkagtn commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/PostgresKeyValueApi.java
> +    private NodeStatus status;
Кажется, что эта переменная должна быть помечена как `volatile`.

2018-03-05 19:42 UTC, alesavin requested changes

2018-03-05 19:42 UTC, alesavin commented on README.md
> +  В силу такой архитектуры, команд выше хватает для корректного запуска всех тестов.
Идею с compose заценил, но тесты наследуемые от KeyValueApiHttpClientTest2 работают при выбранных параметрах  очень долго (у меня не завершились и за 20 минут). После уменьшения DATA_CANDIDATES_MAX/ELEMENTS_NUM/... на порядок прошло за 3 минуты. Это получается некоторое "нагрузочное" тестирование, которое вместе с тем моделирует конкуррентные операции. Давайте переделаем чтобы работало побыстрее, например как тут https://github.com/DB1L/csc-bdse/blob/master/bdse-integration-tests/src/test/java/ru/csc/bdse/kv/KeyValueApiHttpClientTest2.java - далее ведь тоже будут тесты и не хотелось бы ожидать их так долго.

2018-03-07 14:24 UTC, the7winds commented on README.md
> +  В силу такой архитектуры, команд выше хватает для корректного запуска всех тестов.
@alesavin поправил

2018-03-07 16:57 UTC, alesavin approved these changes

2018-03-07 21:51 UTC, merged