CSC BDSE: Task 2
Charmed-BDSE-fans/csc-bdse pull request #4
Opened 2018-03-15 20:56 UTC by LDVSOFT

2018-03-16 18:02 UTC, semkagtn requested changes

2018-03-16 18:02 UTC, semkagtn commented on bdse-integration-tests/src/test/java/ru/csc/bdse/app/AbstractPhoneBookFunctionalTest.java
> +public abstract class AbstractPhoneBookFunctionalTest<R extends Record> {
Ваша реализация позволяет изменять в записи фамилию (surname), в результате чего появляются "спецэффекты".
Примерно такой тест-кейс демонстрирует это:
```java
@Test
public void updateThanGet() {
    final PhoneBookApi<R> api = getPhoneBookApi();

    final R oldRecord = randomRecord();
    final R newRecord = modifyContent(oldRecord); // modifies surname

    final char oldSurnameFirstLetter = getSurname(oldRecord).charAt(0);
    final char newSurnameFirstLetter = getSurname(newRecord).charAt(0);
    assumeTrue(oldSurnameFirstLetter != newSurnameFirstLetter);

    api.put(oldRecord);
    api.put(newRecord);

    final Set<R> actualResult = api.get(oldSurnameFirstLetter);
    final Set<R> expectedResult = Collections.emptySet();
    assertTrue("Actual result: " + actualResult + " but expected: " + expectedResult,
            actualResult == expectedResult); // Actual result: [PhoneBookRecord{name='39134c074cb32cc8', surname='2308b6c471aee012', phone='687d5613287c1f76'}] but expected: []
    }
```

Предполагалось, что менять интерфейс `Record` нельзя (вы добавили метод `getId`). В реализации в  качестве первичного ключа предлагается использовать тройку `(name, surname, nickname)`. Полагаю, из описания задания это было неочевидно.

Следует переделать.

2018-03-16 22:58 UTC, LDVSOFT commented on bdse-integration-tests/src/test/java/ru/csc/bdse/app/AbstractPhoneBookFunctionalTest.java
> +public abstract class AbstractPhoneBookFunctionalTest<R extends Record> {
А, вот такой первичный ключ, понял. Поправим, это должно быть не сложно.

2018-03-17 16:13 UTC, 747mmHg requested changes
-- removed

2018-03-20 16:47 UTC, the7winds commented on bdse-integration-tests/src/test/java/ru/csc/bdse/app/AbstractPhoneBookFunctionalTest.java
> +public abstract class AbstractPhoneBookFunctionalTest<R extends Record> {
@semkagtn, у нас тут возник вопрос. Пусть v2 сделала запись с ником. v1 по прямой совместимости может прочесть её. Пусть она меняет телефонный номер, и затем делает put, но у неё primary key это только имя-фамилия, получается у нас внезапно появилась новая запись, это нормально? (кажется, что да, в задание написано про прямую совместимость на чтение, а не на запись, но всё-таки хочется уточнить)

2018-03-20 17:28 UTC, alesavin commented on bdse-integration-tests/src/test/java/ru/csc/bdse/app/AbstractPhoneBookFunctionalTest.java
> +public abstract class AbstractPhoneBookFunctionalTest<R extends Record> {
Скорее пример такой:
- v2 записала C => {Александр alesavin Савин, 1234567890}, a => {Александр alesavin Савин, 1234567890}
- v1 прочитала по С {Александр Савин, 1234567890}, записала {Александр Савин, 0987654321}
- в сторадже C => {Александр Савин, 0987654321}, a => {Александр alesavin Савин, 1234567890} - то есть вторая запись неконсистентна, но иначе и быть не может. Прямой совместимости (если это корректный термин, совместимость, обычно, для чтения) такого рода невозможно реализовать = этого не требуется

2018-03-20 23:46 UTC, the7winds commented on bdse-integration-tests/src/test/java/ru/csc/bdse/app/AbstractPhoneBookFunctionalTest.java
> +public abstract class AbstractPhoneBookFunctionalTest<R extends Record> {
@alesavin исправили

2018-03-21 10:24 UTC, semkagtn commented on bdse-integration-tests/src/test/java/ru/csc/bdse/app/AbstractPhoneBookFunctionalTest.java
> +        assumeTrue(oldSurnameFirstLetter != newSurnameFirstLetter);
На самом деле такой тест это я привел лишь как демонстрацию проблемы. В идеале здесь стоит обойтись без `assume` и менять `surname` так, чтобы первые символы гарантированно отличались. Это более надежно.

`assume` стоит использовать тогда, когда вероятность его невыполнения крайне мала или когда мы не в состоянии контролировать это условие.

2018-03-21 10:24 UTC, semkagtn commented on bdse-integration-tests/src/test/java/ru/csc/bdse/app/AbstractPhoneBookFunctionalTest.java
> +        int actualNewSize = api.get(oldSurnameFirstLetter).size();
Видимо, здесь хотелось написать:
```java
int actualNewSize = api.get(newSurnameFirstLetter).size();
int expectedNewSize = 0;
```

2018-03-21 10:28 UTC, the7winds commented on bdse-integration-tests/src/test/java/ru/csc/bdse/app/AbstractPhoneBookFunctionalTest.java
> +        int actualNewSize = api.get(oldSurnameFirstLetter).size();
@semkagtn  скорее так
```
int actualNewSize = api.get(newSurnameFirstLetter).size();
int expectedNewSize = 1;
```
т.к. теперь ключи разные и каждая запись присутсвует

2018-03-21 10:55 UTC, semkagtn commented on bdse-integration-tests/src/test/java/ru/csc/bdse/app/AbstractPhoneBookFunctionalTest.java
> +        int actualNewSize = api.get(oldSurnameFirstLetter).size();
Да-да. Верно.
Давайте исправим этот тест, и я вам зачту это задание.

2018-03-21 11:00 UTC, semkagtn approved these changes
Зачтено. Молодцы!

Небольшая просьба: в следующий раз лучше подтягивать изменения из репозитория `alesavin/csc-bdse` в ваш `master`, затем пушить эти изменения в ваш `remote`, а затем уже создавать ветку `csc-bdse-task*`. Тогда в пул-реквесте будут исключительно ваши изменения, что упростит ревью.

2018-03-21 13:28 UTC, merged