CSC BDSE: Task 3
Charmed-BDSE-fans/csc-bdse pull request #5
Opened 2018-04-05 20:13 UTC by LDVSOFT

2018-04-11 09:54 UTC, alesavin requested changes

2018-04-11 09:54 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/node/ConflictResolver.java
> +    Optional<RecordWithTimestamp> resolve(List<Optional<RecordWithTimestamp>> values);
Кажется это неверная сигнатура для случая разбора конфликтов, зачем тут опциональные поля? думаю если нода ответила Optional.empty(), а не RecordWithTimestamp.empty() то ее ответ можно просто игнорировать.

2018-04-11 09:54 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/node/CoordinatedKeyValueApi.java
> +    private <T> List<T> executeTasks(List<Supplier<T>> tasks, int enoughToComplete) {
кажется эта реализация подвержена потенциальным блокировкам, как минимум если делается несколько одновременных запросов. Думаю стоит разделить части scatter-gatter паттерна (http://www.enterpriseintegrationpatterns.com/patterns/messaging/BroadcastAggregate.html), выделив метод "разброса" и получения результатов с реплик:

```
    private <T> List<T> scatter(List<Callable<T>> tasks) {

        return tasks.stream().map(task -> {
            try {
                FutureTask<T> ft = new FutureTask<>(task);
                Thread t = new Thread(ft);
                t.start();
                return ft.get(timeout, TimeUnit.MILLISECONDS);
            } catch (Exception e) {
                LOGGER.warn("Error in processing request, assuming failure", e.getCause());
                return null;
            }
        }).filter(Objects::nonNull).collect(Collectors.toList());
    }

``` 

и далее "собирать" результат с помощью логики CoordinatedKeyValueApi (фильтрация пустых ответов) и conflictResolver.

Или я что-то упустил?

2018-04-11 09:54 UTC, alesavin commented on bdse-kvnode/src/test/java/ru/csc/bdse/kv/node/ConflictResolverTest.java
> +        assertTrue(rec.isDeleted());
спорное утверждение. если все реплики ответили Optional.empty - то ключ на них и не записывался, он не удален

2018-04-11 09:54 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/node/KeyValueApiHttpClient.java
> +public class KeyValueApiHttpClient implements InternalKeyValueApi {
Не очень хорошо менять поставляемый код, нужно стараться этого избегать. В данном случае лучше сделать свою реализацию, которая внутри поднимает несколько  KeyValueApiHttpClient - для каждой из нод. 

А почему появился InternalKeyValueApi? Чем его специфика отличается от KeyValueApi?

2018-04-11 09:54 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/node/CoordinatedKeyValueApi.java
> +    private byte[] encodeRecord(RecordWithTimestamp record) {
Хорошо бы вынести это в какой-то отдельный класс RecordWithTimestampSerDe

2018-04-11 09:54 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/node/ConflictResolver.java
> +    Optional<RecordWithTimestamp> resolve(List<Optional<RecordWithTimestamp>> values);
Вместе с тем вы поменяли мою ошибочную сигнатуру, конечно же вместо
```
 RecordWithTimestamp resolve(in: Set<RecordWithTimestamp>);
```
должно быть
```
 RecordWithTimestamp resolve(in: List<RecordWithTimestamp>);
```
иначе нельзя было бы ресолвить по значению у большинства

2018-04-11 09:54 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/config/KeyValueApiControllerConfig.java
> +    public static final String INTERNAL_KV_PREFIX = "/internal/";
А перемещение базового API (первое задание) на новый контекст точно необходимо? Лучше без особой необходимости этого не делать, сохраняя обратную совместимость. Нет ли возможности оставить KeyValueApiController на / (GET /key-value/{key}), а контроллер с репликами на /replicated (GET /replicated/key-value/{key})?

2018-04-11 09:54 UTC, alesavin commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/CoordinatedKeyValueApiTest.java
> +public class CoordinatedKeyValueApiTest extends AbstractCoordinatedKeyValueApiTest {
Хорошие тесты, честно отключают/включают ноды. Но есть и минус в таком подходе - работают они очень долго для простых операций (на моей машине CoordinatedKeyValueApi бежит 13 минут). Все время тратится на реинициализацию контейнеров при UP/DOWN командах. Может тут есть возможность прооптимизировать?

2018-04-11 18:01 UTC, LDVSOFT commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/node/CoordinatedKeyValueApi.java
> +    private <T> List<T> executeTasks(List<Supplier<T>> tasks, int enoughToComplete) {
Так кажется всё хорошо? Поток принявший запрос ждёт, пока в `executorService` случится одно из двух: нужное число задач выполнится или выполнится задача "убить по таймауту". Откуда проблема с блокировками? Проблемы могут быть только с 10k connections, но для этого надо переезжать на асинхронный стек, что поделать: координатор по определению имеет I/O bottleneck.

2018-04-11 19:02 UTC, LDVSOFT commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/node/KeyValueApiHttpClient.java
> +public class KeyValueApiHttpClient implements InternalKeyValueApi {
Это для запуска. Надо каким-то способом разделять реализации, которые предоставляют, хм, работающее `KeyValueApi` и координатор-декоратор `CoordinatedKeyValueApi`.

2018-04-11 19:05 UTC, LDVSOFT commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/config/KeyValueApiControllerConfig.java
> +    public static final String INTERNAL_KV_PREFIX = "/internal/";
Так можно было бы сделать, но мы хотели выставить наружу "ready-to-use" API, а не внутреннее, хранящее `RecordWithTimestamp` вместо данных. В этом смысле для пользователя хранилища всё обратно совместимо.

2018-04-11 19:06 UTC, LDVSOFT commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/node/CoordinatedKeyValueApi.java
> +    private byte[] encodeRecord(RecordWithTimestamp record) {
Там же просто `ObjectMapper` используется? Подобный код есть в предоставленных контроллерах.

2018-04-11 19:53 UTC, LDVSOFT commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/CoordinatedKeyValueApiTest.java
> +public class CoordinatedKeyValueApiTest extends AbstractCoordinatedKeyValueApiTest {
Это трудно оптимизировать, не врываясь внутрь фреймворка тестирования, @the7winds наверное больше может сказать.

2018-04-12 08:07 UTC, the7winds commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/CoordinatedKeyValueApiTest.java
> +public class CoordinatedKeyValueApiTest extends AbstractCoordinatedKeyValueApiTest {
@alesavin там вроде была проблема с тем, что контейнеры перезапускаются на каждый тест и это всё упиралось в то, что junit не умеет делать инициализацию-освобождение ресурсов на весь класс после конструктора

2018-04-12 15:35 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/node/CoordinatedKeyValueApi.java
> +    private <T> List<T> executeTasks(List<Supplier<T>> tasks, int enoughToComplete) {
я правильно понял что ScheduledExecutorService увеличит число тредов в пуле при необходимости? тогда да, вы правы, это будет работать, я как-то интуитивно ожидал ForkJoinPool и попплатился. Можно сделать чуть компактнее как тут https://github.com/DB1L/csc-bdse/blob/c0b0f4021d1f5c6188354b8dbff51172ac2c7a6d/bdse-kvnode/src/main/java/ru/csc/bdse/coordinator/CoordinatorKeyValueApi.java#L107 но сути не меняет

2018-04-12 15:43 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/node/CoordinatedKeyValueApi.java
> +    private byte[] encodeRecord(RecordWithTimestamp record) {
Сходу не припомнил где в поставляемых используется, но не будут спорить - лучше сериализацию/десериализацию выносить в отдельные структуры, так и тестировать легче

2018-04-12 15:45 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/config/KeyValueApiControllerConfig.java
> +    public static final String INTERNAL_KV_PREFIX = "/internal/";
А такая конфигурация не будет работать:
```
GET /key-value/{key} // PostgresKeyValueApi
GET /replicated/key-value/{key} // CoordinatedKeyValueApi 
```

2018-04-12 15:50 UTC, alesavin commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/CoordinatedKeyValueApiTest.java
> +public class CoordinatedKeyValueApiTest extends AbstractCoordinatedKeyValueApiTest {
да, я это понял. как вариант можно попробовать сделать replicated тест с in-memory базовой реализацией - он должен работать сильно быстрее.

2018-04-12 15:56 UTC, LDVSOFT commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/config/KeyValueApiControllerConfig.java
> +    public static final String INTERNAL_KV_PREFIX = "/internal/";
Её можно сделать, но мы сделали именно не так ради прозрачности у использующих (подключились по старому юрлу, а там дичь) в клиентах. Можно и обратно поменять.

2018-04-12 15:58 UTC, LDVSOFT commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/CoordinatedKeyValueApiTest.java
> +public class CoordinatedKeyValueApiTest extends AbstractCoordinatedKeyValueApiTest {
А у нас разве не так?) Строчка 56.

2018-04-12 16:04 UTC, LDVSOFT commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/node/CoordinatedKeyValueApi.java
> +    private <T> List<T> executeTasks(List<Supplier<T>> tasks, int enoughToComplete) {
Ну тут ещё очень просилось написать `CompletableFuture.orTimeout`  из Java 9.
По сути мы здесь написали реализацию её же из JDK 9, они там так же делают.

2018-04-12 18:53 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/config/KeyValueApiControllerConfig.java
> +    public static final String INTERNAL_KV_PREFIX = "/internal/";
Я просто считал что к координатору будет отдельный клиент, отличный от изначального для Key-value Persistent Storage Unit (при этом не запрещено внутри первого использовать второй). Тогда все потребители работают обратно-совместимо (например приложение, которое делали во втором задании)

2018-04-12 18:57 UTC, alesavin commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/CoordinatedKeyValueApiTest.java
> +public class CoordinatedKeyValueApiTest extends AbstractCoordinatedKeyValueApiTest {
Тут какое-то недопонимание, для InMemoryKeyValueApi не нужно останавливать контейнер, можно просто отправить action(node, NodeAction.DOWN)

2018-04-12 21:52 UTC, LDVSOFT commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/CoordinatedKeyValueApiTest.java
> +public class CoordinatedKeyValueApiTest extends AbstractCoordinatedKeyValueApiTest {
Ой, точняк) @the7winds ?

2018-04-13 07:30 UTC, LDVSOFT commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/node/CoordinatedKeyValueApi.java
> +    private <T> List<T> executeTasks(List<Supplier<T>> tasks, int enoughToComplete) {
Да, он создаёт больше потоков, но меньше чем cores не отпускает.

2018-04-14 11:28 UTC, the7winds commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/CoordinatedKeyValueApiTest.java
> +public class CoordinatedKeyValueApiTest extends AbstractCoordinatedKeyValueApiTest {
@LDVSOFT, мы разве оставливаем на DOWN? мне казалось мы после посланного DOWN  просто игнорируем запросы

2018-04-15 10:20 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/node/ConflictResolver.java
> +    Optional<RecordWithTimestamp> resolve(List<RecordWithTimestamp> values);
а почему в результате Optional? Кажется такого не должно быть если на входе не пустой список. Возможен вариант если возвращается tombstone, но это уже не забота разрешателя конфликтов:

```
        final RecordWithTimestamp result = conflictResolver.resolve(records);
        if (result.isDeleted()) {
            return Optional.empty();
        } else {
            return Optional.of(result.payload());
        }
```

2018-04-15 20:39 UTC, alesavin approved these changes
Принято без доделок, снял один балл

2018-04-16 15:14 UTC, merged